config/routes.rb
Onkeeband::Application.routes.draw do
  
  resources :events, :path => "shows", :path_names => { :new => 'schedule', :edit => 'modify' }

  devise_for :user
  
  devise_scope :user do 
    get "/login" => "devise/sessions#new"
    get "/logout" => "devise/sessions#destroy"
  end
  
  resources :users, :only => [:index, :show]

  post '/subscribe' => 'subscription#subscribe'
  get '/unsubscribe/:scptn_hash' => 'subscription#unsubscribe'
  get '/subscriptions' => 'subscription#index'

  scope :controller => :pages do 
    get '/history'   => 'pages#history'
    get '/profiles'      => 'pages#profiles'
    get '/photos'      => 'pages#photos'
    get '/support'      => 'pages#support'
    get '/contact'      => 'pages#contact'
    
    scope '/management' do
      get 'lenny'.parameterize  => 'pages#lenny'
    end
    
    scope '/washington-dc' do
      get 'aubrey'   => 'pages#aubrey'
      get 'david'    => 'pages#david'
      get 'lenny'    => 'pages#lenny'
      get 'cornell'    => 'pages#cornell'
      get 'rhube'    => 'pages#rhube'
    end
    
    scope '/boston' do
      get 'carl'     => 'pages#carl'
      get 'darren'   => 'pages#darren'
      get 'greg'     => 'pages#greg'
      get 'lenny'    => 'pages#lenny'
      get 'rasheed'  => 'pages#rasheed'
    end
    
    scope '/featured-guest' do
      get 'michael'     => 'pages#michael'
    end
    
    
  end
  
  get 'download/vcard' => 'file#vcard'
  
  
  root  :to => "pages#home", :via => :get
  

end

app/views/shared/_boston_band_sidebar.haml
%section#profile-nav 
	%h3.bottom Band Management
	%section#managment
		%article.profile
			%a{:href => "#"}
				= image_tag("profiles/greg1-bw.jpg")
				%footer
					%h4.name.bottom Greg Silva
					%h5.title Bass Guitarist
		%article.profile
			%a{:href => "#"}
				= image_tag("profiles/darren1-bw.jpg")
				%footer
					%h4.name.bottom Darren Fry
					%h5.title Drummer
		%article.profile
			%a{:href => "#"}
				= image_tag("profiles/rasheed1-bw.jpg")
				%footer
					%h4.name.bottom Rasheed Meadows
					%h5.title Saxophone
		%article.profile
			%a{:href => "#"}
				= image_tag("profiles/carl2-bw.jpg")
				%footer
					%h4.name.bottom Carl Parks
					%h5.title Percussionist
		%article.profile
			%a{:href => "/boston/lenny"}
				= image_tag("profiles/lenny2-bw.jpg")
				%footer
					%h4.name.bottom Lenny McLean
					%h5.title Composer / Keyboardist

app/views/shared/_dc_band_sidebar_nav.haml
%section#profile-nav 
	%h3.bottom Washington D.C. Area Band
	%section#dc-band
		%article.profile
			%a{:href => "/washington-dc/aubrey"}
				= image_tag("profiles/aubrey2-bw.jpg")
				%footer
					%h4.name.bottom Aubrey McKoy
					%h5.title Bass Guitarist
		%article.profile
			%a{:href => "/washington-dc/cornell"}
				= image_tag("profiles/cornell1-bw.jpg")
				%footer
					%h4.name.bottom Cornell Webb
					%h5.title Drummer
		%article.profile
			%a{:href => "/washington-dc/rhube"}
				= image_tag("profiles/rhube1-bw.jpg")
				%footer
					%h4.name.bottom Ralph "Rhube" Peters 
					%h5.title Saxophone
		%article.profile
			%a{:href => "/washington-dc/david"}
				= image_tag("profiles/david1-bw.jpg")
				%footer
					%h4.name.bottom David Dillard
					%h5.title Percussionist
		%article.profile
			%a{:href => "/washington-dc/lenny"}
				= image_tag("profiles/lenny2-bw.jpg")
				%footer
					%h4.name.bottom Lenny McLean
					%h5.title Composer / Keyboardist

app/views/shared/_event.html.haml
%li 
	%aside.event-date
		%p.weekday-name= event.date.to_time.to_s(:weekday_name)
		%p.month-name= event.date.to_time.to_s(:month_name)
		%p.day-of-month= event.date.day.ordinalize
		%p.year= event.date.year if event.date.year < Time.now.year
		%p.time-interval
			%span.begin-time= event.begin_time.to_s(:event_time)
			%span -
			%span.end-time= event.end_time.to_s(:event_time)
	
	%article.event-details
		%header
			%h4.venue-name= link_to event.venue_name, event.website_url, {:target => "_blank"}
			- if event.pub_date
				%time.post-date{:pubdate => "pubdate"}= "Posted: #{event.pub_date.to_s(:event_pub_date)}"
			- else
				%time.post-date.unpublished{:pubdate => "pubdate"}= "Unpublished"
		%address
			- unless event.private_event
				%p.first_line= event.address.first_line
				- if event.address.second_line
					%p.second_line= event.address.second_line
			%p.city= event.address.city
			%p.state= ", #{event.address.state}" if event.address.state
			%p.country= event.address.country if !Address::STATE_COUNTRIES.include?(event.address.country)
		%footer.clear
			- unless event.private_event
				%p.notes= event.notes
				%p.cost
					%span= "#{(event.admission_type == "cover"? "Cover Charge" : "Tickets")}:"
					%span= "#{event.price > 0.0? number_to_currency(event.price) : " Free"}"
			- else
				%p.notes Private Event
				
			- if current_user && controller.controller_name == "events"
				%p.admin
					%span= link_to 'Show', event
					%span= link_to 'Edit', edit_event_path(event)
					%span= link_to 'Delete', event, :confirm => 'Are you sure?', :method => :delete

app/views/shared/_google_analytics.html.erb
<!-- Google Analytics -->
	<script type="text/javascript">
		var _gaq = _gaq || [];
	  	_gaq.push(['_setAccount', 'UA-20928063-1']);
	  	_gaq.push(['_trackPageview']);

	  	(function() {
	    	var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
	    	ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
	    	var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
	  	})();
	</script>

app/views/shared/_masthead.html.haml
#masthead
	= link_to "<h1>On Kee Jazz Band</h1>".html_safe, root_path
	
	%blockquote#tagline
		%p &ldquo;The Kee of life is how you play it...&rdquo;
		%p -On Kee Band
	
	= render 'shared/primary_nav' if Rails.env == "development"

app/views/shared/_media_player.html.haml
#music
	%h2 Sounds of OnKee Band
	#player-holder
	

app/views/shared/_mgmt_sidebar_nav.haml
%section#profile-nav 
	%h3.bottom Band Management
	%section#managment
		%article.profile.clearfix
			%a{:href => "/management/lenny"}
				= image_tag("profiles/lenny2-bw.jpg")
				%footer
					%h4.name.bottom Lenny McLean
					%h5.title Founder / Band Leader
		%article.profile
			%a{:href => "/management/anita"}
				= image_tag("profiles/anita3-bw.jpg")
				%footer
					%h4.name.bottom Anita Truitt
					%h5.title Executive Manager
		/ %article.profile
		/ 	%a{:href => "#", :style => "cursor: default"}
		/ 		= image_tag("profiles/david-r1-bw.jpg")
		/ 		%footer
		/ 			%h4.name.bottom David Romaine
		/ 			%h5.title Manager

app/views/shared/_primary_nav.html.haml
%nav#main-nav
	%li{:id => "home"}
		%a{:href => "/"}= "Home"
	%li{:id => "history"}
		%a{:href => "/history"}= "History"
	%li{:id => "profiles"}
		%a{:href => "/profiles"}= "Profiles"
	%li{:id => "shows"}
		= link_to "Shows", events_path
	%li{:id => "photos"}
		%a{:href => "/photos"}= "Photos"
	/ %li{:id => "support"}
	/ 	%a{:href => "/support"}= "Support"
	%li{:id => "contact"}
		%a{:href => "/contact"}= "Contact"

app/views/shared/_subscription_sidebar.haml
%section#newsletter 
	%h3.bottom Subscribe to the OKB Newsletter
	%p.bottom
		Subscribe to the On Kee Band Newsletter 
		and stay in the loop with upcoming 
		events and whereabouts.
		
	= form_for :subscription, :url => subscribe_url, :protocol => "http", :method => :post, :remote => true, :html => {:id => 'subscription_form'}  do |form|
		= form.text_field :email, :size => 22, :maxlength => 50, :value => 'Your Email Address'
		= form.submit "Subscribe"
	
	%p.small 
		%span.red *
		We will not sell or freely distribute your email address.
	= image_tag 'spinner_trans2.gif', :id => 'spinner', :style => "display:none;position:absolute;top:70px;left:130px;"