config/routes.rb
Onkeeband::Application.routes.draw do
  
  resources :events, :path => "shows", :path_names => { :new => 'schedule', :edit => 'modify' }

  devise_for :user
  
  devise_scope :user do 
    get "/login" => "devise/sessions#new"
    get "/logout" => "devise/sessions#destroy"
  end
  
  resources :users, :only => [:index, :show]

  post '/subscribe' => 'subscription#subscribe'
  get '/unsubscribe/:scptn_hash' => 'subscription#unsubscribe'
  get '/subscriptions' => 'subscription#index'

  scope :controller => :pages do 
    get '/history'   => 'pages#history'
    get '/profiles'      => 'pages#profiles'
    get '/photos'      => 'pages#photos'
    get '/support'      => 'pages#support'
    get '/contact'      => 'pages#contact'
    
    scope '/management' do
      get 'lenny'.parameterize  => 'pages#lenny'
    end
    
    scope '/washington-dc' do
      get 'aubrey'   => 'pages#aubrey'
      get 'david'    => 'pages#david'
      get 'lenny'    => 'pages#lenny'
      get 'cornell'    => 'pages#cornell'
      get 'rhube'    => 'pages#rhube'
    end
    
    scope '/boston' do
      get 'carl'     => 'pages#carl'
      get 'darren'   => 'pages#darren'
      get 'greg'     => 'pages#greg'
      get 'lenny'    => 'pages#lenny'
      get 'rasheed'  => 'pages#rasheed'
    end
    
    scope '/featured-guest' do
      get 'michael'     => 'pages#michael'
    end
    
    
  end
  
  get 'download/vcard' => 'file#vcard'
  
  
  root  :to => "pages#home", :via => :get
  

end

app/models/event.rb
class Event
  include Mongoid::Document
  include Mongoid::MultiParameterAttributes
  include Mongoid::Timestamps::Created
  
  field :venue_name,      :type => String
  field :date,            :type => Date
  field :begin_time,      :type => Time
  field :end_time,        :type => Time
  field :website_url,     :type => String
  field :price,           :type => Float, :default => 0.00
  field :admission_type,  :type => String
  field :notes,           :type => String
  field :private_event,   :type => Boolean, :default => false
  field :published,       :type => Boolean, :default => false
  field :pub_date,        :type => Time
  
  scope :published, where(published: true)
  scope :ordered, desc(:date)
  
  before_save :set_pubdate
  
  embeds_one :address
  
  accepts_nested_attributes_for :address
  
  delegate :first_line, :second_line, :city, :state, :country, :to => :address
  
  ADMISSION_TYPES = {"Ticket Event" => :ticket, "Cover Charge" => :cover}
  WEB_URL_REGEX = /^(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?$/ix
  PRICE_REGEX = /^\d+??(?:\.\d{0,2})?$/
  
  validates_presence_of :venue_name, :date, :message => "can't be blank"
  validates :date, :uniqueness => { :message => "please select another date" }
  
  with_options :unless => :is_private? do |event|
    event.validates :begin_time, :presence => true
    event.validates :end_time, :presence => true
    event.validate :begin_time_before_end_time, :unless => "begin_time.blank? || end_time.blank?"
  end
  
  validates :website_url, :format => {:with => WEB_URL_REGEX, :message => "check the URL, should start with http:// or https:// "}, :allow_blank => true
  validates :price, :format => {:with => PRICE_REGEX, :message => "must be a valid dollar amount."}, :allow_blank => true
  validate :event_date_not_in_past, :unless => "date.blank?"
  
  paginates_per 5
  
  def is_private?
    self.private_event
  end
  
  private
  
  def set_pubdate
    if self.pub_date.nil? && self.published
      self.pub_date = Time.now
    elsif self.pub_date && !self.published
      self.pub_date = nil
    end
  end
    
  def event_date_not_in_past
    errors.add(:date, "can't be in the past") if self.date < Date.yesterday
  end
  
  def begin_time_before_end_time
    if self.begin_time > self.end_time
      unless end_time.hour == 0 && end_time.min == 0
        errors.add(:begin_time, "can't be after event's End Time")
        errors.add(:end_time, "can't be before event's Begin Time")
      end
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_filter :authenticate_user!, :except => [:index, :show]
  ssl_exceptions :index
  ssl_allowed :index
  
  # GET /events
  # GET /events.json
  def index
    @events = current_user ? Event.ordered.page(params[:page]) : Event.published.ordered.page(params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @events }
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/new
  # GET /events/new.json
  def new
    @event = Event.new
    @event.build_address

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(params[:event])

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render json: @event, status: :created, location: @event }
      else
        format.html { render action: "new" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.json
  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event has been removed' }
      format.json { head :ok }
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.haml
= simple_form_for @event do |f|
  
	= f.input :venue_name, :label => 'Venue Name', :input_html => {:autofocus => "autofocus"}

	=# f.input :date, :as => :date, :label => 'Date', :start_year => Time.now.year, :ampm => true, :order => [:month, :day, :year], :date_separator => "/", :prompt => true
	
	= f.input :date, :label => 'Date', :input_html => {:class => 'date-field'}
	
	= f.input :begin_time, :as => :time, :label => 'Begin Time', :minute_step => 15, :ampm => true, :prompt => true

	= f.input :end_time, :as => :time, :label => 'End Time', :minute_step => 15, :ampm => true, :prompt => true
	
	= f.input :website_url, :label => 'Website URL'

	= f.input :price, :label => 'Price', :input_html => {:class => 'short-field', :value => number_with_precision(f.object.price, :precision => 2)}

	= f.input :admission_type, :label => 'Admission Type', :collection => Event::ADMISSION_TYPES.map, :prompt => "Select Admission"
  	
	= f.simple_fields_for :address do |addr_fields|
 
		= addr_fields.input :first_line, :label => 'Address Line 1', :hint => "(e.g. Physical Street Address)"

		= addr_fields.input :second_line, :label => 'Address Line 2', :hint => "(e.g. Bldg, Suite)"

		= addr_fields.input :city, :label => 'City'

		= addr_fields.input :state, :label => 'State / Province', :input_html => {:class => 'short-field', :maxlength => 2}

		= addr_fields.input :country
	
	= f.input :private_event, :as => :boolean, :label =>'Private Occasion', :hint => "(Excludes street address and time displayed to public)"

	= f.input :published, :as => :boolean, :label =>'Publish', :hint => "(Make available to the public)"

	= f.input :notes, :as => :text, :label => 'Notes:', :input_html => {:size => "55x10"}

	.actions
		= link_to 'Cancel', events_path
		= f.submit 'Save'
		

app/views/events/edit.html.haml
- content_for :main_content do 
	%h1 Editing Show

	= render 'form'

	= link_to 'Show', @event
	\|
	= link_to 'Back', events_path
end

app/views/events/index.html.haml
- @page_class = "events"

- content_for :page_heading do
	%h2#page-heading.events Band Events
	%h3#page
end

- content_for :main_content do

	%p
		- if current_user
			= link_to '+', new_event_path, {:class => "plus-button"}
			
	%ol#events.listing-box
		= render :partial => "shared/event", :collection => @events
		
	= paginate @events
end

app/views/events/new.html.haml
- content_for :main_content do 
	%h2 Schedule A New Show

	= render 'form'
end

- content_for :page_heading do
	/ %h2#page-heading.history Shows
end

app/views/events/show.html.haml
- content_for :main_content do
	/ %p#notice notice

	%p
		%b Venue:
		= @event.venue_name
	%p
		%b Date:
		= @event.date
	%p
		%b Begin:
		= @event.begin_time
	%p
		%b End:
		= @event.end_time
	%p
		%b Url:
		= @event.website_url
	%p
		%b Cover charge:
		= @event.admission_type
	%p
		%b Notes:
		= @event.notes
	%p
		%b Published:
		= @event.published

	= link_to 'Edit', edit_event_path(@event)
	\|
	= link_to 'Back', events_path
end 