config/routes.rb
Onkeeband::Application.routes.draw do
  
  resources :events, :path => "shows", :path_names => { :new => 'schedule', :edit => 'modify' }

  devise_for :user
  
  devise_scope :user do 
    get "/login" => "devise/sessions#new"
    get "/logout" => "devise/sessions#destroy"
  end
  
  resources :users, :only => [:index, :show]

  post '/subscribe' => 'subscription#subscribe'
  get '/unsubscribe/:scptn_hash' => 'subscription#unsubscribe'
  get '/subscriptions' => 'subscription#index'

  scope :controller => :pages do 
    get '/history'   => 'pages#history'
    get '/profiles'      => 'pages#profiles'
    get '/photos'      => 'pages#photos'
    get '/support'      => 'pages#support'
    get '/contact'      => 'pages#contact'
    
    scope '/management' do
      get 'lenny'.parameterize  => 'pages#lenny'
    end
    
    scope '/washington-dc' do
      get 'aubrey'   => 'pages#aubrey'
      get 'david'    => 'pages#david'
      get 'lenny'    => 'pages#lenny'
      get 'cornell'    => 'pages#cornell'
      get 'rhube'    => 'pages#rhube'
    end
    
    scope '/boston' do
      get 'carl'     => 'pages#carl'
      get 'darren'   => 'pages#darren'
      get 'greg'     => 'pages#greg'
      get 'lenny'    => 'pages#lenny'
      get 'rasheed'  => 'pages#rasheed'
    end
    
    scope '/featured-guest' do
      get 'michael'     => 'pages#michael'
    end
    
    
  end
  
  get 'download/vcard' => 'file#vcard'
  
  
  root  :to => "pages#home", :via => :get
  

end

app/views/pages/aubrey.html.haml
- @page_class = "profiles"

- content_for :main_content do
	%section#main.column.span-12.profiles
		%h2.name.bottom Aubrey McKoy
		%h3.title.bottom 
			Bass Guitarist 
			%span.location Washington D.C. Band
		
		%p
			= image_tag("profiles/aubrey5.jpg", :alt => "Testing", :title => "", :class => 'append-bottom')
			
			%span.drop-cap A
			ubrey McKoy also known to the band as &ldquo;Big Percy&rdquo;, first became interested in playing the Bass Guitar at the age of 13. Aubrey grew up in Harlem New York where he was influenced by 
			many styles of music. This included R&B, Jazz and Latin music that play daily through the airways and in the streets. Aubrey was later introduced 
			to Rock and Gospel music. Aubrey first learned to play by ear listening to music on the radio. He later had the benefit of the tutoring from 
			Ramone Rodriguez, who worked as a music teacher at Boys Harbor in New York.
		%p 
			Aubrey went on to play in many young R&B groups and a college band (Unique Productions) made up of students at Boston College. Aubrey had his 
			first recording opportunity playing with a Gospel Group in New York called Selwin Rawls and the Eternal light singers. Aubrey moved to the west 
			coast, where he continued with his love of music and created a group with Jerome Rice called East Meets West, which performed in several clubs 
			in the Los Angeles area.
		%p 
			He later moved again to Dallas, Texas, where he spiritually matured at Oak Cliff Bible Fellowship. Aubrey became a Praise Musician for the Church 
			playing every Wednesday and Sunday. There, he met other musicians and became a member of a Gospel/Jazz Group called A Breath of Fresh Air. The 
			group played at many Gospel events and dinner clubs for several years.  Aubrey is married and living in Southern Maryland. Aubrey met Lenny McLean 
			through an old college friend, and now has joined him in continuing the On Kee Jazz Band music journey. It is a joy to find yourself through music 
			and to find others who also share in this expression of yourself and love.
			
end

- content_for :sidebar do
	%aside#sidebar.history.column.span-6
		= render :partial => "shared/subscription_sidebar"
				
		= render :partial => "shared/dc_band_sidebar_nav"
end

- content_for :page_heading do
	%h2#page-heading.profiles Profiles & Bios
end

app/views/pages/contact.html.haml
- @page_class = "contact"

- content_for :main_content do
	%section#main.column.span-12.contact
		= image_tag("okb-600x399.png", :class => "matted-photo", :alt => "On Kee Jazz Band", :title => "On Kee Jazz Band")
end

- content_for :sidebar do
	%aside#sidebar.contact.column.span-6
		=# render :partial => "shared/subscription_sidebar"
		
		%section#booking 
			%h3 Booking Contacts
				
			%article.agent
				%p.name.bottom Lenny McLean
				%p.title.bottom Founder / Band Leader
				%p.email.bottom Email: lenny@onkeeband.com
				%p.phone Phone: (508) 740-2470
				=link_to "Lenny McLean - Vcard Download", download_vcard_url(:card => "lenny"), {:class => "icon vcard"}
		
		%section#promo
			%h3 Promotion Package
			%p At your convenience, our promo package is available for download in the following formats:
			=link_to "ONKEE Promo Pkg - Word format", "/docs/onkeeband-promo-pkg.doc", {:class => "icon word"}
			=link_to "ONKEE Promo Pkg - PDF format", "/docs/onkeeband-promo-pkg.pdf", {:class => "icon pdf"}

end

- content_for :page_heading do
	%h2#page-heading.contact Contact Us
end

app/views/pages/cornell.html.haml
- @page_class = "profiles"

- content_for :main_content do
	%section#main.column.span-12.profiles
		%h2.name.bottom Cornell Webb
		%h3.title.bottom 
			Drummer
			%span.location Washington D.C. Band

		%p
			= image_tag("profiles/cornell1.jpg", :alt => "Testing", :title => "", :class => 'append-bottom')

			%span.drop-cap C
			ornell Webb was born & raised in Washington DC.  He is the product of a very musical family with a strict church up bringing.  Cornell started 
			playing at the age of 6 years old in his family church & from there would go on to play for elementary school & community choirs.  
		%p 
			Being blessed to be raised in the presence & watchful eye of  his uncle & mentor  Andre "Blues" Webb  he would get to meet many of music's 
			heavywights knowing that this call on his life would be the road that he would want to take.  
		%p 
			He has been blessed to share the stage & experciences 
			with musical greats such as The Trey Eley, Marcus Mitchell Project, Tamika "Love" Jones, Maysa Leak, & the legendary Godfather of Gogo Chuck Brown. 
			You can currently catch him laying the groove behind up and coming jazz groups On Kee &amp; The Jazz Boyz.
end

- content_for :sidebar do
	%aside#sidebar.history.column.span-6
		= render :partial => "shared/subscription_sidebar"

		= render :partial => "shared/dc_band_sidebar_nav"
end

- content_for :page_heading do
	%h2#page-heading.profiles Profiles & Bios
end

app/views/pages/darren.html.haml
%h1 Darren

%p Lorem ipsum...

app/views/pages/greg.html.haml
%h1 Greg

%p Lorem ipsum...

app/views/pages/history.html.haml
- @page_class = "history"

- content_for :main_content do
	%section#main.column.span-12.history
		%p	
			%span.drop-cap T
			he On Kee Jazz Band has been providing smooth and jazzy live entertainment since 1993.  The band initially played live with national recording group, 
			“Classic Example”, headed by Maurice Starr.  In 1994, OnKee realized that they had a common love for jazz and original music.  While pursuing that 
			direction and the willingness to take risks, the band pursued respectable Jazz Clubs in the Boston metropolitan area.After hard work, and partnering 
			with various talented musicians, OnKee developed a strong fan base that allowed them to perform at various venues.
			 
			= image_tag("history-1359-bw.jpg", :alt => "Testing", :title => "First performance at 1359 Jazz Club", :class => "left top bottom")
			
			OnKee often performed at the Historic Connolly’s Jazz Club in Roxbury and the 1359 Jazz Club in Cambridge, MA.  Once the band discovered a balance 
			of Jazz standards and original music, OnKee began to perform at Ryles Jazz Club in Cambridge and G Clef in Providence, RI which was once a powerhouse 
			for showcases of national and local acts.  
			
		%p	
			= image_tag("history-ryles-bw.jpg", :alt => "Testing", :title => "First performance at Ryles Jazz Club", :class => "right top bottom") 
			
			Some of the	band’s most outreaching performances took place during the year of 1996, opening for National recording Jazz Artists, Jeff Lober and 
			Bob James at G Clef.  In 1997, the band performed at the 1997 NSBE (National Society of Black Engineers) Convention at the Prudential Building in 
			Boston.  In addition, they maintain a firm commitment and dedication to the community by donating their time to the Special Olympics, an event held 
			annually at Stonehill College in Easton, MA.  
			
			= image_tag("history-singers-bw.jpg", :alt => "Testing", :title => "The first On Kee Singers", :class => "left top bottom") 
			
			The band was very fortunate to perform four years in a row at this event until Lenny relocated to Maryland.  Other events include playing at a 
			benefit for the New England Shelter for Homeless Veterans at the House of Blues Club in Cambridge and in 1998 performed at the “Steppin Out Gala” 
			a fundraiser for the Dimock Community Health Center.

		%p 
			In 2004, OnKee performed at the Democratic Convention in honor of the National Education Association.  In October 2005, OnKee proudly introduced its 
			first CD release “Giving Back” which helped to raise money for the Lupus Foundation in the New England area.  OnKee has since produced two other CD 
			releases; “Live at Mars” and “Positivity.”  The bands fourth CD was recently released in the Fall of 2010.
		%p 
			Over the past several years, OnKee supported various events to include a Lupus Foundation fundraiser held in Glen Burnie, MD April 2008 and have 
			recently provided weekly performances at the Stonefish Grill, Peachez Lounge &amp; Caf&eacute; (both located in Upper Marlboro, MD) and the Westin Hotel in 
			Alexandria, VA.
			
		%p 
			The jazzy sounds of OnKee were initially due to the band members located within the Boston, MA metro area:  Lenny McLean, keyboards and band leader; Bass Greg Silva 
			from Quincy; Drums Darin Fry from Cambridge; Saxophones Rasheed Meadows from Boston; two Percussionists, Carl Parks from Dorchester and Moses from 
			Bridgewater. 
			 
		%p 	
			After relocating to Maryland, Lenny formed a second OnKee Jazz Band within the DMV (D.C., Maryland, Virginia) metropolitan area.  The current members of the band 
			include the following:  Bass, Aubrey McCoy from Waldorf, MD; Drums, Kenny Trusty from Baltimore, MD; Saxophones, Ralph &ldquo;Rhube&rdquo; Peters from Lanham, MD; 
			and Percussion, Dave Dillard.  The band members are full-time employed and are part-time 
			musicians willing to explore new ideas and arrangements to Jazz standards as well as create their own style.  The members are inspired and influenced 
			by many artists such as Joe Sample, Elvin Jones, Sonny Rollins, Don Alias and Jaco Pastorius.  Since relocating to Maryland, Lenny is blessed to have 
			musicians willing to continue the OnKee legacy by playing in both Boston and Washington D.C. bands.
			
		%p 
			OnKee is committed to family, a firm spiritual foundation, and the continuation of providing unique and jazzy music to its fan base across the Eastern 
			Seaboard, the country, and abroad.	
end

- content_for :sidebar do
	%aside#sidebar.history.column.span-6
		
		=# render :partial => "shared/subscription_sidebar"
		
		%section#history-gallery.bottom
			%article.mini-gallery.append-bottom
				%h3 Featured in the Press
				%a{:class => "history-sidebar-group", :rel => "group1", :href => "#{asset_path 'history/article1.jpg'}"}
					= image_tag "history/article1_tb_bw.jpg", :size => "90x116"
				%a{:class => "history-sidebar-group", :rel => "group1", :href => "#{asset_path 'history/article2.jpg'}"}
					= image_tag "history/article2_tb_bw.jpg", :size => "90x116"
				%a{:class => "history-sidebar-group", :rel => "group1", :href => "#{asset_path 'history/article3.jpg'}"}
					= image_tag "history/article3_tb_bw.jpg", :size => "90x116"
			
			%article.mini-gallery.bottom
				%h3 Support for Lupus Foundation
				%a{:class => "history-sidebar-group", :rel => "group1", :href => "#{asset_path 'history/Lupus1_resize.jpg'}"}
					= image_tag "history/Lupus1_tb_bw.jpg", :size => "90x116"
				%a{:class => "history-sidebar-group", :rel => "group1", :href => "#{asset_path 'history/Lupus2_resize.jpg'}"}
					= image_tag "history/Lupus2_tb_bw.jpg", :size => "90x116"
				%a{:class => "history-sidebar-group", :rel => "group1", :href => "#{asset_path 'history/Lupus3_resize.jpg'}"}
					= image_tag "history/Lupus3_tb_bw.jpg", :size => "90x116"
				%a{:class => "history-sidebar-group", :rel => "group1", :href => "#{asset_path 'history/Lupus4_resize.jpg'}"}
					= image_tag "history/Lupus4_tb_bw.jpg", :size => "90x116"
				%a{:class => "history-sidebar-group", :rel => "group1", :href => "#{asset_path 'history/Lupus5_resize.jpg'}"}
					= image_tag "history/Lupus5_tb_bw.jpg", :size => "90x116"
				%a{:class => "history-sidebar-group", :rel => "group1", :href => "#{asset_path 'history/Lupus6_resize.jpg'}"}
					= image_tag "history/Lupus6_tb_bw.jpg", :size => "90x116"
end

- content_for :page_heading do
	%h2#page-heading.history Behind the Band History
end

- content_for :extra_css do 
	=# stylesheet_link_tag 'jquery.fancybox-1.3.4.css', :media => "screen, projection"
end
	

- content_for :fancy_box_js do
	
	=# javascript_include_tag 'jquery.fancybox-1.3.4.pack.js'
	=# javascript_include_tag 'jquery.easing-1.3.pack.js'
	=# javascript_include_tag 'jquery.mousewheel-3.0.4.pack.js'
	
	:javascript
		$(window).load(function() {
			$("a.history-sidebar-group").fancybox({
				'transitionIn'	:	'elastic',
				'transitionOut'	:	'elastic',
			});
		});
end
	

app/views/pages/home.html.haml
- @page_class = "home"

- content_for :main_content do
	%section#main.column.span-18.home 
		%section#media.span-9.left
			%h2 ONKEE Media
			
			/ %article#music
			/ 	%header
			/ 		%h3.gold.left Sounds Of
			/ 		%h3.light.clearfix The Band
			/ 	%p#player Sorry.  Your browser does not support flash-enabled applications
			%article#video
				/ %header
				/ 	%h3.gold.left Previous   
				/ 	%h3.light.clearfix ONKEE Footage
					
				%div#video_player Loading the video player...
				
		
		%section#calendar.span-9.right
			%h2 Our Next Gig
		
			/ %header
			/ 	%h3.gold.left Come Experience
			/ 	%h3.light.clearfix ONKEE Live	
									
			%ol#events
				= render :partial => "shared/event", :collection => @events 
				

					
					
				/ %li
				/ 	%time.date 
				/ 		%span.dayname Wednesday
				/ 		%span.month.gold Dec
				/ 		%span.day.light 21
				/ 	%aside.venue.light
				/ 		%h4.gold.bottom 
				/ 			%a{:href => "http://www.moulindeparismd.com/", :target => "_blank"} Moulin de Paris
				/ 		%address	
				/ 			%span.addr1 31 Magothy Beach Rd. Suite 105
				/ 			%span.addr2 Pasadena, MD
				/ 		%p
				/ 			%span.time 2:00pm - 5:00pm
				/ 			%span.note Private Event
				/ %li
				/ 	%time.date 
				/ 		%span.dayname Friday
				/ 		%span.month.gold Dec
				/ 		%span.day.light 16
				/ 	%aside.venue.light
				/ 		%h4.gold.bottom 
				/ 			%a{:href => "http://www.starwoodhotels.com/alofthotels/property/overview/index.html?propertyID=3050", :target => "_blank"} Aloft Hotel Arundel Mills
				/ 		%address	
				/ 			%span.addr1 7520 Teage Rd.
				/ 			%span.addr2 Hanover, MD
				/ 		%p
				/ 			%span.time 7:00pm - 10:00pm
				/ 			%span.note No Cover Charge
				/ %li#next
				/ 	%time.date 
				/ 		%span.dayname Friday
				/ 		%span.month.gold Dec
				/ 		%span.day.light 09
				/ 	%aside.venue.light
				/ 		%h4.gold.bottom 
				/ 			%a{:href => "http://bigeasylounge.webs.com/", :target => "_blank"} Big Easy Restaurant &amp; Lounge
				/ 		%address	
				/ 			%span.addr1 9820 Liberty Rd
				/ 			%span.addr2 Randallstown, MD
				/ 		%p
				/ 			%span.time 8:30pm - 12:00am
				/ 			%span.note Toy Drive held for children at Kennedy Krieger Institute <br> Please feel free to donate a toy for this special occasion.
				/ 			%span.note Cover Charge: $5.00
				/ %li
				/ 	%time.date 
				/ 		%span.dayname Saturday
				/ 		%span.month.gold Oct
				/ 		%span.day.light 08
				/ 	%aside.venue.light
				/ 		%h4.gold.bottom 
				/ 			%a{:href => "http://www.rylesjazz.com", :target => "_blank"} Ryles Jazz Club
				/ 		%address	
				/ 			%span.addr1 212 Hampshire Street
				/ 			%span.addr2 Cambridge, MA 
				/ 		%p
				/ 			%span.time 9:00pm - 12:00am
				/ 			%span.note  7th Annual LUPUS Foundation Fundraiser
				/ 			%span.note  Sponsored by The LUPUS Foundation of New England
				/ %li
				/ 	%time.date 
				/ 		%span.dayname Sunday
				/ 		%span.month.gold Sep
				/ 		%span.day.light 25
				/ 	%aside.venue.light
				/ 		%h4.gold.bottom 
				/ 			%a{:href => "http://www.sheraton.com/bwi", :target => "_blank"} BWI Sheraton Jazz Brunch
				/ 		%address	
				/ 			%span.addr1 1100 Old Elkridge Landing Road
				/ 			%span.addr2 Linthicum Heights, MD 
				/ 		%p
				/ 			%span.time 11:00am - 2:00pm
				/ 			%span.note  Feat. Cheryl Goodman from WEAA Radio 88.9 FM Baltimore
				/ 			%span.note  Tickets: $25.00 advance -- $30.00 at door
				/ %li
				/ 	%time.date 
				/ 		%span.dayname Thursday
				/ 		%span.month.gold Aug
				/ 		%span.day.light 11
				/ 	%aside.venue.light
				/ 		%h4.gold.bottom 
				/ 			%a{:href => "http://www.eubieblake.org", :target => "_blank"} Eubie Blake Jazz & Cultural Center
				/ 		%address	
				/ 			%span.addr1 847 North Howard Street
				/ 			%span.addr2 Baltimore, MD
				/ 		%p
				/ 			%span.time 6:00pm - 8:00pm
				/ 			%span.note  Ghana African Mission Photo Exhibit by Tana Lopez
				
				
				
				
				/ %li
				/ 	%time.date 
				/ 		%span.month.gold Aug
				/ 		%span.day.light 06
				/ 	%aside.venue.light
				/ 		%h4.gold.bottom 
				/ 			Annual Fish Fry
				/ 		%address	
				/ 			%span.addr2 Bowie, MD
				/ 		%p
				/ 			%span.time 6:00pm - 10:00pm
				/ 			%span.note  Private Event
				/ %li
				/ 	%time.date 
				/ 		%span.month.gold Jul
				/ 		%span.day.light 16
				/ 	%aside.venue.light
				/ 		%h4.gold.bottom 
				/ 			Red Element (formerly Si Salsa)
				/ 		%address	
				/ 			%span.addr1 1700 Reisterstown Rd
				/ 			%span.addr2 Pikesville, MD
				/ 		%p
				/ 			%span.time 8:00pm - 11:30pm
				/ 			%span.note Cover Charge: $10
				/ %li
				/ 	%time.date 
				/ 		%span.month.gold Jul
				/ 		%span.day.light 08
				/ 	%aside.venue.light
				/ 		%h4.gold.bottom 
				/ 			%a{:href => "http://www.lenfantplazahotel.com", :target => "_blank"} L'Enfant Plaza Hotel
				/ 		%address	
				/ 			%span.addr1 480 L'Enfant Plaza, SW
				/ 			%span.addr2 Washington, D.C.
				/ 		%p
				/ 			%span.time 5:00pm - 9:00pm
				/ 			%span.note No Cover Charge
				/ %li
				/ 	%time.date 
				/ 		%span.month.gold Jun
				/ 		%span.day.light 10
				/ 	%aside.venue.light
				/ 		%h4.gold.bottom 
				/ 			%a{:href => "http://www.thecarlyleclub.com/", :target => "_blank"} The Carlyle Club
				/ 		%address	
				/ 			%span.addr1 411 John Carlyle Street
				/ 			%span.addr2 Alexandria, VA 
				/ 		%p
				/ 			%span.time 8:00pm - 11:00pm
				/ 			%span.note $15 in advance, $20 at door
				/ %li
				/ 	%time.date 
				/ 		%span.month.gold Jun
				/ 		%span.day.light 05
				/ 	%aside.venue.light
				/ 		%h4.gold.bottom 
				/ 			%a{:href => "http://www.latinpalace.com", :target => "_blank"} Latin Palace
				/ 		%address
				/ 			%span.addr1 509 South Broadway
				/ 			%span.addr2 Baltimore, MD
				/ 		%p
				/ 			%span.time 8:00pm - 11:00pm
				/ 			%span.note $15 in advance, $20 at door
				/ %li
				/ 	%time.date 
				/ 		%span.month.gold May
				/ 		%span.day.light 30
				/ 	%aside.venue.light
				/ 		%h4.gold.bottom 
				/ 			%a{:href => "http://www.wpbradio.com", :target => "_blank"} Live Interview on WPB Radio
				/ 		%address
				/ 			%span.city Baltimore, MD
				/ 		%p
				/ 			%span.time 11:00am - 3:00pm
				/ 			%span.note Listen and call in live!
				/ %li
				/ 	%time.date 
				/ 		%span.month.gold May
				/ 		%span.day.light 28
				/ 	%aside.venue.light
				/ 		%h4.gold.bottom 
				/ 			%a{:href => "http://www.lenfantplazahotel.com", :target => "_blank"} L'Enfant Plaza Hotel
				/ 		%address	
				/ 			%span.addr1 480 L'Enfant Plaza, SW
				/ 			%span.addr2 Washington, D.C.
				/ 		%p
				/ 			%span.time 6:00pm - 10:00pm
				/ 			%span.note No Cover Charge
				/ %li
				/ 	%time.date 
				/ 		%span.month.gold May
				/ 		%span.day.light 20
				/ 	%aside.venue.light
				/ 		%h4.gold.bottom 
				/ 			%a{:href => "http://bigeasylounge.webs.com/", :target => "_blank"} Big Easy Restaurant &amp; Lounge
				/ 		%address	
				/ 			%span.addr1 9820 Liberty Rd
				/ 			%span.addr2 Randallstown, MD
				/ 		%p
				/ 			%span.time 9:00pm - 12:00am
				/ 			%span.note No Cover Charge
 
				
end	




- content_for :band_photo_slide do
	%section#slide-show
		%div#slide-matting
			%div#slider.nivoSlider
				= image_tag("slider-photos/slider-photo-5.png", :alt => "On Kee Jazz Band", :title => "")
				= image_tag("slider-photos/slider-photo-6.png", :alt => "On Kee Jazz Band", :title => "")
				= image_tag("slider-photos/candid-group3.jpg", :alt => "On Kee Jazz Band", :title => "")
				= image_tag("slider-photos/hands-onkees.png", :alt => "On Kee Jazz Band", :title => "")
				= image_tag("slider-photos/candid-group2.jpg", :alt => "On Kee Jazz Band", :title => "")
				= image_tag("slider-photos/slider-photo-3.jpg", :alt => "On Kee Jazz Band", :title => "")
				
end

- content_for :tagline do

	%blockquote#tagline 
		%p.bottom The Kee of life is how you play it...
		%p.bottom --On Kee Band
end

- content_for :extra_css do
	=# stylesheet_link_tag 'nivo-slider', :media => "screen, projection"
	=# stylesheet_link_tag 'video-js', :media => "screen, projection", :title => "Video JS"
end

- content_for :nivo_slider_js do

	=# javascript_include_tag 'jquery.nivo.slider.pack'
	:javascript
		$(window).load(function() {
			$('#slider').nivoSlider({effect:'random', pauseTime:7000});
		});
end


- content_for :audio_player_js do 
	
	=# javascript_include_tag 'audio-player'
	%script{:async => true, :defer => true}
		AudioPlayer.setup("#{asset_path 'player.swf'}", {width: 290});
end


- content_for :audio_playlist do

	%script{:async => true, :defer => true}
		AudioPlayer.embed("player", 
		{
		soundFile: "#{asset_path 'audio/home-playlist/song5.mp3'}, #{asset_path 'audio/home-playlist/song4.mp3'}, #{asset_path 'audio/home-playlist/song2.mp3'}", 
		titles: "Inner Strength, Quick to the Madness, Live at Si Salsa!",
		transparentpagebg: "yes",
		});
end

/ - content_for :video_js do 
/ 	
/ 	= javascript_include_tag 'video-js'
/ 	
/ 	:javascript
/ 		$(window).load(function() {
/ 			VideoJS.setupAllWhenReady();
/ 		});
/ end

- content_for :jwplayer do 
	
	=# javascript_include_tag 'jwplayer'
	
	:javascript		
		jwplayer("video_player").setup({
		"modes": [
		        {type: "flash", src: "#{asset_path 'video_player.swf'}"},
				{type: "html5"}
		    ],
		playlist: [
			{ file: "#{asset_path 'video/OKB-video4.m4v'}", image: "#{asset_path 'video-poster.png'}", author: "On Kee", title: "On Kee - Let It Flow", description: "BWI Sheraton Hotel  |  Linthicum, MD", duration: "7:26" },
			{ file: "#{asset_path 'video/OKB-video3.m4v'}", image: "#{asset_path 'video-poster.png'}", author: "On Kee", title: "On Kee - Butterfly", description: "BWI Sheraton Hotel  |  Linthicum, MD", duration: "11:50" },
			{ file: "#{asset_path 'video/OKB-video1.m4v'}", image: "#{asset_path 'video-poster.png'}", author: "On Kee", title: "On Kee - Impressions (On Kee Style)", description: "Reginald F. Lewis Museum  |  Baltimore, MD", duration: "9:02" }
		], 
		"playlist.position": "bottom", 
		"playlist.size": 150,
		provider: "http",
		plugins: {
			"sharing-3": {
				link: "http://www.onkeeband.com"
			}
		},
		volume: 50,
		height: 425,
		width: 485,
		skin: "#{asset_path 'glow/glow.xml'}"
		});
end
	

app/views/pages/photos.html.haml
- @page_class = "photos"

- content_for :main_content do
	%section#main.column.span-18.gallery
		%div#set1
			- (0..49).each do |number|
				- photo_name = "%03d" % number
				- file_fullpath = "gallery/Set1/resized/#{photo_name}.jpg"
				- file_url = asset_path file_fullpath
				- thumb_fullpath = "gallery/Set1/thumbs/#{photo_name}_thumb.jpg"
				- thumb_url = asset_path thumb_fullpath
				%a{:href => file_url} <img style="display: none" src="#{thumb_url}">
		%div.append-bottom#set1-gallery.thumbs
end

- content_for :page_heading do
	%h2#page-heading.photos Photos
end

	
- content_for :galleria_js do
	=# javascript_include_tag 'galleria'
	=# javascript_include_tag 'galleria.lightbox.js'
	
	:javascript
		// Load theme
		$('#set1-gallery').galleria({
			width: 600,
			height: 600,
			data_source: '#set1',
			extend: function() {
				this.bind(Galleria.LOADFINISH, function(e) {
					$(e.imageTarget).click(this.proxy(function(e) {
						e.preventDefault();
						this.next();
					}))
				})
			},
			transition: 'slide',
			transition_speed: 525,
			thumb_crop: true,
			keep_source: true,
			lightbox: true,
			data_config: function(img) {
				return {
					description: $(img).next('.caption').html()
				}
			}
		});
end

app/views/pages/rasheed.html.haml
%h1 Rasheed

%p Lorem ipsum...